import { DataBankItem, ReportItem, CommitteeItem } from '../types';

export const dataBankItems: DataBankItem[] = [
  {
    id: 'db-agri-gva-share',
    category: 'Agriculture',
    metric: 'Agriculture & Allied Sectors Share in National GVA',
    value: '18.2%',
    year: '2023-24 (Provisional)',
    unit: '% of Gross Value Added',
    source: 'National Statistical Office (NSO), MoSPI',
    definition: 'Proportion of economic value generated by farming, forestry, livestock, and fishing relative to India’s total Gross Value Added.',
    examRelevance: 'Essential baseline statistic for GS-3: Contrasts 18% economic output with employing ~45% of national workforce (structural mismatch).',
    lastVerified: '2026-01-15'
  },
  {
    id: 'db-forest-cover-isfr',
    category: 'Environment',
    metric: 'Total Forest and Tree Cover in India',
    value: '24.62% (80.9 Million Hectares)',
    year: 'ISFR (FSI Assessment)',
    unit: '% of Geographical Area',
    source: 'Forest Survey of India (FSI), MoEFCC',
    definition: 'Combined area under forest cover (canopy density > 10% on land >= 1 ha) and tree cover (tree patches outside recorded forests < 1 ha).',
    examRelevance: 'Target set by National Forest Policy 1988 is 33% of geographical area; MP has largest forest cover by area; Mizoram by percentage (~84.5%).',
    lastVerified: '2026-02-01'
  },
  {
    id: 'db-renewable-capacity',
    category: 'Climate',
    metric: 'Non-Fossil Fuel Installed Electric Capacity',
    value: '195.5 GW (~45% of total grid)',
    year: '2024-25',
    unit: 'Gigawatts (GW)',
    source: 'Central Electricity Authority (CEA) / MNRE',
    definition: 'Cumulative generation capacity from Solar, Wind, Large Hydro, Biomass, Nuclear, and Small Hydro.',
    examRelevance: 'Tracks progress towards COP26 Panchamrit target of 500 GW non-fossil capacity by 2030.',
    lastVerified: '2026-02-10'
  },
  {
    id: 'db-lwe-districts',
    category: 'Security',
    metric: 'Security-Related Expenditure (SRE) LWE-Affected Districts',
    value: 'Reduced to 38 Districts',
    year: '2024 Status',
    unit: 'Districts count (down from 126 in 2014)',
    source: 'Ministry of Home Affairs (MHA) Annual Report',
    definition: 'Districts officially notified as experiencing Left Wing Extremist violence, qualifying for specialized central security reimbursements.',
    examRelevance: 'Quantifies dramatic shrinking of the Red Corridor in internal security answers; 90% of violent incidents are now concentrated in 10-12 core districts.',
    lastVerified: '2026-01-25'
  },
  {
    id: 'db-logistics-cost',
    category: 'Infrastructure',
    metric: 'National Logistics Cost as % of GDP',
    value: '7.8% - 8.9%',
    year: 'NCAER / DPIIT Study',
    unit: '% of GDP',
    source: 'National Council of Applied Economic Research (NCAER) & DPIIT',
    definition: 'Total cost incurred across transportation, warehousing, inventory holding, and supply chain administration in the economy.',
    examRelevance: 'Targeted to be reduced to global benchmark levels (~6-7%) under the National Logistics Policy (NLP) and PM Gati Shakti National Master Plan.',
    lastVerified: '2026-02-05'
  },
  {
    id: 'db-gross-npa-ratio',
    category: 'Economy',
    metric: 'Gross Non-Performing Assets (GNPA) Ratio of Scheduled Commercial Banks',
    value: '2.8%',
    year: 'RBI Financial Stability Report',
    unit: '% of Gross Advances',
    source: 'Reserve Bank of India (RBI)',
    definition: 'Ratio of bad loans (defaulted or close to default) to the total advances issued by commercial banks.',
    examRelevance: 'Reflects the transformation of the "Twin Balance Sheet Syndrome" (2015-18 when GNPA peaked at 11.5%) into the "Twin Balance Sheet Advantage".',
    lastVerified: '2026-01-20'
  }
];

export const reportItems: ReportItem[] = [
  {
    id: 'rep-economic-survey-latest',
    reportName: 'Economic Survey 2023-24 / 2024-25',
    publisher: 'Chief Economic Adviser, Ministry of Finance',
    year: 2024,
    majorFindings: [
      'Growth is robust, powered by public capex and healthy private balance sheets, but corporate sector must step up productive hiring.',
      'The Indian economy needs to generate ~7.85 million non-farm jobs annually until 2030 to absorb structural migration.',
      'Agriculture has demonstrated an average 4.18% annual growth rate over the past five years despite erratic monsoons.'
    ],
    importantData: [
      'Projected Real GDP growth: 6.5% - 7.0%',
      'Gross Fixed Capital Formation (GFCF) share in GDP: ~31%',
      'Credit growth maintained at 15%+ YoY'
    ],
    gs3Relevance: 'The supreme source for economic analysis, fiscal statistics, and structural transformation arguments in GS-3.',
    prelimsFacts: [
      'Authored by the Chief Economic Adviser and tabled by Finance Minister in Parliament one day prior to Union Budget.',
      'First Economic Survey was presented for 1950-51; until 1964 it was presented together with the Budget.'
    ],
    mainsArguments: [
      'Quote chapter on "Deregulating for Growth": Urging state governments to dismantle bureaucratic compliance thickets for MSMEs.',
      'Use the analysis on female labour force participation to balance arguments on rural self-employment quality.'
    ],
    sourceUrl: 'https://www.indiabudget.gov.in/economicsurvey/'
  },
  {
    id: 'rep-ipcc-ar6-synthesis',
    reportName: 'IPCC Sixth Assessment Report (AR6 Synthesis)',
    publisher: 'Intergovernmental Panel on Climate Change (IPCC / WMO / UNEP)',
    year: 2023,
    majorFindings: [
      'Human activities have unequivocally caused global warming, with global surface temperature reaching 1.1°C above 1850-1900 levels.',
      'Global greenhouse gas emissions must peak before 2025 and be slashed by 43% by 2030 to keep warming limited to 1.5°C.',
      'South Asia is an acute climate hotspot: Coastal cities face compounding risks of sea level rise, cyclones, and extreme wet-bulb temperatures exceeding 31°C.'
    ],
    importantData: [
      'Remaining carbon budget for 1.5°C is rapidly exhausting (~500 GtCO2 as of 2020).',
      'Over 3.3 to 3.6 billion people live in contexts that are highly vulnerable to climate change.'
    ],
    gs3Relevance: 'Authoritative scientific backing for all answers on climate impacts, IPCC Working Group II (Adaptation) and Working Group III (Mitigation).',
    prelimsFacts: [
      'IPCC was established in 1988 by World Meteorological Organization (WMO) and UNEP.',
      'IPCC does not conduct its own research; it synthesizes published scientific literature across thousands of peer-reviewed papers.'
    ],
    mainsArguments: [
      'Cite IPCC findings to argue for the operationalization of the Loss & Damage Fund established at COP28.',
      'Emphasize Climate Justice: Historical cumulative emissions of developed countries (Annex-I) consumed 80% of the carbon budget.'
    ],
    sourceUrl: 'https://www.ipcc.ch/assessment-report/ar6/'
  },
  {
    id: 'rep-rbi-fsr',
    reportName: 'Financial Stability Report (FSR)',
    publisher: 'Reserve Bank of India (RBI)',
    year: 2024,
    majorFindings: [
      'The Indian financial system remains resilient with multi-decade high Capital to Risk-Weighted Assets Ratio (CRAR at 16.8%).',
      'Macro-stress tests reveal that Scheduled Commercial Banks are well-capitalized to absorb severe macroeconomic shocks without regulatory breach.',
      'Warns against the rapid surge in unsecured retail loans (personal loans, credit cards) and high inter-connectedness of NBFCs.'
    ],
    importantData: [
      'CRAR: 16.8% (against statutory requirement of 9% and Basel III norm of 8%)',
      'System-wide Gross NPA ratio: 2.8%; Net NPA ratio: 0.6%'
    ],
    gs3Relevance: 'Direct input for GS-3 Monetary Policy, Banking Sector Health, and Macroeconomic Stability.',
    prelimsFacts: [
      'FSR is published biannually (June and December) by the Reserve Bank of India.',
      'Reflects collective assessment of the Sub-Committee of Financial Stability and Development Council (FSDC).'
    ],
    mainsArguments: [
      'Demonstrate how Prompt Corrective Action (PCA) framework and Insolvency and Bankruptcy Code (IBC 2016) resolved legacy bad loans.',
      'Discuss risks posed by shadow banking and digital fintech apps lending without underwriting standards.'
    ],
    sourceUrl: 'https://www.rbi.org.in'
  }
];

export const committeeItems: CommitteeItem[] = [
  {
    id: 'comm-shanta-kumar',
    name: 'Shanta Kumar High-Level Committee on FCI Restructuring',
    year: 2015,
    chairperson: 'Shanta Kumar (Former Union Food Minister)',
    subject: 'Restructuring of Food Corporation of India (FCI), procurement reforms, buffer stocking, and Targeted PDS (TPDS).',
    keyRecommendations: [
      'Hand over grain procurement to states with surplus capacity (e.g. Punjab, Haryana, MP) and focus FCI operations on Eastern states (Bihar, UP, West Bengal, Assam) where distress selling occurs.',
      'Reduce NFSA coverage from 67% of population to 40% (strictly confining food subsidies to genuine BPL households).',
      'Gradually introduce Direct Benefit Transfer (DBT) of food subsidy (cash transfers) in cities with population > 1 million.',
      'Outsource storage, grain handling, and silo construction to private operators via PPP under Viability Gap Funding.'
    ],
    implementationStatus: 'Partial: Central government initiated digital modernization of FCI depots, silo development, and One Nation One Ration Card (ONORC), but rejected lowering NFSA coverage.',
    gs3Relevance: 'The primary committee to cite for any question on PDS reforms, food subsidy leakage, FCI operational losses, and buffer stock management.',
    pyqsLinked: ['UPSC Mains 2019 GS-3 (Food security and PDS)', 'UPSC Mains 2021 GS-3 (FCI buffer stock and economic cost of wheat)'],
    source: 'Ministry of Consumer Affairs, Food and Public Distribution'
  },
  {
    id: 'comm-ashok-dalwai',
    name: 'Committee on Doubling Farmers\' Income (DFI)',
    year: 2018,
    chairperson: 'Dr. Ashok Dalwai (CEO, National Rainfed Area Authority)',
    subject: 'Comprehensive 14-volume roadmap for doubling real income of Indian farmers by 2022-23.',
    keyRecommendations: [
      'Shift strategy from traditional production-centric agriculture to income-centric agri-business and value chain creation.',
      'Upgrade rural periodic haats into Gramin Agricultural Markets (GrAMs) linked to e-NAM to bypass physical APMC cartels.',
      'Promote 10,000 new Farmer Producer Organizations (FPOs) to provide economies of scale for smallholders.',
      'Incentivize Secondary Agriculture (beekeeping, mushroom cultivation, sericulture, agri-tourism) to augment non-crop farm income.',
      'Promote Model Agricultural Land Leasing Act drafted by NITI Aayog to secure rights of tenant cultivators without land dispossession.'
    ],
    implementationStatus: 'Substantially integrated into policy: 10,000 FPOs scheme launched; PM-KISAN direct income support enacted; Agri Infra Fund (₹1 lakh cr) operationalized.',
    gs3Relevance: 'The universal benchmark committee for all agriculture and farmer welfare answers in GS-3.',
    pyqsLinked: ['UPSC Mains 2017 GS-3', 'UPSC Mains 2020 GS-3', 'UPSC Mains 2022 GS-3'],
    source: 'Ministry of Agriculture and Farmers Welfare Reports'
  },
  {
    id: 'comm-shekatkar',
    name: 'Lt. Gen. D.B. Shekatkar Committee on Defence Reforms',
    year: 2016,
    chairperson: 'Lt. Gen. (Retd.) D.B. Shekatkar',
    subject: 'Enhancing combat capability and rebalancing defence expenditure of the Armed Forces.',
    keyRecommendations: [
      'Creation of the post of Chief of Defence Staff (CDS) and establishment of Integrated Theatre Commands.',
      'Restructuring Army base workshops and closing military farms and army postal units to optimize revenue spend.',
      'Deploying advanced surveillance technology and electronic sensors to optimize manpower deployment on static border pickets.',
      'Increasing defence capital expenditure to at least 2.5% to 3% of GDP to accelerate modernization.'
    ],
    implementationStatus: 'High: Creation of CDS (2019), disbanding of 130-year-old Military Farms, ongoing rollout of Joint Theatre Commands, and Agnipath scheme.',
    gs3Relevance: 'Indispensable citation for GS-3 Security Forces, defence procurement indigenization, and theaterization of Armed Forces.',
    pyqsLinked: ['UPSC Mains 2018 GS-3 (Defence modernization)', 'UPSC Mains 2022 GS-3 (Integrated Theatre Commands)'],
    source: 'Ministry of Defence Press Releases'
  }
];

export const caseStudyLibrary = [
  {
    id: 'case-hiware-bazar',
    title: 'Hiware Bazar: Transforming a Drought-Struck Hamlet into an Affluent Water Sanctuary',
    category: 'Water & Agriculture',
    location: 'Ahmednagar District, Maharashtra',
    problem: 'In the early 1990s, Hiware Bazar received under 400 mm annual rainfall, leading to 90% water deficit, crop failure, distress migration, alcoholism, and crime.',
    intervention: 'Community-led watershed management under the leadership of Sarpanch Popatrao Pawar: Banned water-guzzling sugarcane and borewells; constructed 52 earthen bunds, continuous contour trenches, and percolation tanks.',
    technology: 'Water budgeting: Annually calculating village water balance before sowing season. If rainfall is low, farmers collectively agree to sow only pulses and millets.',
    outcome: 'Groundwater table rose from 70-80 feet depth to under 20-25 feet. Zero families below poverty line; over 50 village millionaires (crorepatis) created through dairy and organic onion farming.',
    lesson: 'Community social fencing and participatory water governance can eradicate drought vulnerability without expensive external engineering.',
    source: 'NITI Aayog Best Practices Compendium & Down To Earth'
  },
  {
    id: 'case-sikkim-organic',
    title: 'Sikkim: World’s First 100% Certified Organic State',
    category: 'Sustainable Agriculture',
    location: 'Sikkim, Eastern Himalayas',
    problem: 'Excessive chemical fertilizers and synthetic pesticides contaminating mountain soil, harming river aquatic life, and increasing health risks in fragile Himalayan ecology.',
    intervention: 'Phased legislative transition starting in 2003: Complete ban on sale and import of synthetic fertilizers, chemical pesticides, and GMO seeds under Sikkim Agricultural Produce Act.',
    technology: 'Soil health cards, on-farm vermicomposting, bio-fertilizers, and organic bio-control agents certified under National Programme for Organic Production (NPOP).',
    outcome: 'Awarded the UN FAO Future Policy Gold Award (2018). Enhanced biodiversity, boosted eco-tourism, and earned premium prices for Sikkim Cardamom and Ginger exports.',
    lesson: 'Political willpower backed by gradual phase-in, farmer bio-input training, and organic certification can establish agro-ecological food sovereignty.',
    source: 'UN Food and Agriculture Organization (FAO) & Government of Sikkim'
  },
  {
    id: 'case-indore-swachh',
    title: 'Indore: India’s Cleanest City for 7 Consecutive Years',
    category: 'Waste & Urban Pollution',
    location: 'Indore Municipal Corporation (IMC), Madhya Pradesh',
    problem: 'Massive open dumpsites, unsegregated municipal solid waste exceeding 1,200 tonnes/day, choking air quality, and low civic compliance.',
    intervention: '100% source segregation into 6 separate streams (Wet, Dry, Plastic, E-waste, Domestic Hazardous, Sanitary); decentralized GPS-tracked door-to-door collection tippers.',
    technology: 'Asia’s largest Bio-CNG plant (Gobar-Dhan plant at Devguradia): 550 tonnes/day wet organic waste converted into compressed bio-methane powering 150 city city buses.',
    outcome: 'Eliminated all secondary waste collection bins (Bin-Free City); reclaimed 100 acres of dumpsite land through complete bio-mining of 15 lakh tonnes legacy waste.',
    lesson: 'Behavioral change (Nudge theory) combined with strict municipal enforcement, zero-tolerance spot fines, and financially viable waste-to-wealth conversion generates lasting urban resilience.',
    source: 'Ministry of Housing and Urban Affairs (MoHUA) Swachh Survekshan Report'
  }
];

export const internationalComparisons = [
  {
    domain: 'High-Speed Rail & Disaster Resilience',
    india: 'Mumbai-Ahmedabad Bullet Train (MAHSR under construction via NHSRCL and JICA partnership).',
    country: 'Japan (Shinkansen Network)',
    contrast: 'Japan\'s Shinkansen has carried over 10 billion passengers since 1964 with ZERO passenger fatalities, operating UrEDAS (Urgent Earthquake Detection and Alarm System) that automatically cuts power and applies emergency brakes seconds before seismic P-waves arrive.',
    lessonForIndia: 'Incorporate automated seismograph interlocks into Indian high-speed rail and Dedicated Freight Corridors.'
  },
  {
    domain: 'Water Scarcity & Desalination',
    india: 'Over-extracts 250+ BCM groundwater; low wastewater treatment capacity (<30% in urban centers).',
    country: 'Israel',
    contrast: 'Israel recycles >85% of its municipal wastewater for agriculture (vs Spain at 20% and world at <10%); meets 80% of domestic drinking water requirements through reverse osmosis seawater desalination powered by solar energy.',
    lessonForIndia: 'Adopt mandatory wastewater recycling standards for non-potable cooling and municipal parks; establish desalination hubs in coastal industrial corridors (Chennai, Surat).'
  },
  {
    domain: 'Semiconductor Fabrication Ecosystem',
    india: 'Launching nascent domestic fabs under India Semiconductor Mission (Tata-PSMC at Dholera, Micron ATMP).',
    country: 'Taiwan (TSMC Foundry Model)',
    contrast: 'Taiwan manufactures over 60% of global semiconductor microchips and >90% of advanced sub-7nm chips. Driven by the "Hsinchu Science Park" cluster linking universities (NTHU), government research institutes (ITRI), and specialized chemical/gas supply vendors within a 50 km radius.',
    lessonForIndia: 'Semiconductors require comprehensive ecosystem clustering (ultra-pure water, specialty gases, photoresist chemicals) rather than isolated fabrication plants.'
  }
];
